[package]
name = "rpkg"
authors = ["Alberson da Silva Miranda <albersonmiranda@hotmail.com>"]
version = "0.3.1"
description = "A lightweight CLI wrapper around Rscript for installing R packages from CRAN or elsewhere"
edition = "2021"
license = "MIT"
repository = "https://github.com/albersonmiranda/rip"
homepage = "https://github.com/albersonmiranda/rip"
documentation = "https://docs.rs/rpkg"
readme = "README.md"
keywords = ["r", "cli", "rscript", "cran", "installer"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
strsim = "0.11"
